### ISSUE TITLE
streams don't end anymore

### ISSUE THREAD

**Issue by yocontra** [tunnckoCore/vinyl-filter-since#5]
just tried updating to the latest, seems streams that pipe to filter since never end now

**Comment by yocontra** [comment]
whats the reason for not using through2 here?

**Comment by yocontra** [comment]
https://github.com/brycebaril/through2-filter

**Comment by tunnckoCore** [comment]
> whats the reason for not using through2 here?

cuz @shinnn PR #3

**Comment by tunnckoCore** [comment]
@contra please try `v2.0.0` and report back? I can return `through2`

or maybe because using Streams3 api, behind `readable-stream@2`?

hm.. that make sense. When I rethink it, i should change it to use old streams?

**Comment by yocontra** [comment]
@tunnckoCore it was 2.0.0 that i was having issues with. downgrading to 1.0.0 fixed it, the streams end again

**Comment by tunnckoCore** [comment]
Actually.. i dont know what of them to use, lol.

> downgrading to 1.0.0 fixed it

okey, I'll check.

**Comment by tunnckoCore** [comment]
Strange. Can you give example? I guess it is because of the bump of `through2@0.6.3` to `2.0.0`, I cant see other reason for now.

**Comment by yocontra** [comment]
@tunnckoCore vinyl-fs. updating vinyl-filter-since makes the src test that uses it fail because the stream never emits an end event.

probably the through2 update, looking into it as well. updating to 2.0.0 on some other stuff is causing no end events just finish

**Comment by tunnckoCore** [comment]
@contra okey, i'll try and fix it in a bit.

It's strange, cuz `vinyl-filter-since` have that tests exactly from vinyl-fs.

**Comment by tunnckoCore** [comment]
@contra okey, there's no logic. it is tested and works with streams3 on 0.10, 0.12, 1.x.x and 2.x.x, that's the idea of these userland `readable-stream` and `through2` packages..

Look carefully the tests of `vinyl-fs`? damn that streams, lol.

**Comment by tunnckoCore** [comment]
Damn, okey. I figured it out. Instead of `this.push(file)` should be `next(null, file)` as was in `v1.0.x`

I will release it as `v2.0.2`.

But definitely you should clear up the tests of `vinyl-fs` and `glob-stream`, imo.

**Comment by shinnn** [comment]
Yeah, my bad. I should have not add `return` to this line: https://github.com/tunnckoCore/vinyl-filter-since/commit/745649471e25cc6ae0bead91e183ce5b2ee43283#diff-168726dbe96b3ce427e7fedce31bb0bcR24

**Comment by yocontra** [comment]
Still seeing it on 2.0.2

**Comment by shinnn** [comment]
@contra Could you create a small script or repository that can reproduce the problem you're running into?

**Comment by yocontra** [comment]
its a really really easy bug to demonstrate, end event simply never happens. finish happens, end does not.

https://github.com/contra/vinyl-filter-since-is-broken

**Comment by tunnckoCore** [comment]
@contra i cant realize why it happens, seriously. It seems using `through2@0` also dont emits `end`, so we missing something and it's not streams2/3 problem.

**Comment by shinnn** [comment]
[gulp-coffee](), a gulp plugin that [depends on through2 v0.6.x](https://github.com/wearefractal/gulp-coffee/blob/e6291adce767e77b41c062719e9f1f4d0d589353/package.json#L16), also doesn't emit `end` event in this case.

``` js
'use strict';

var coffee = require('gulp-coffee');
var through2 = require('through2');
var File = require('vinyl');

var success = new File({
  cwd: '/',
  base: '/test/',
  path: '/test/file.coffee',
  contents: new Buffer('1'),
  stat: {
    mtime: new Date('2015-03-17 13:27:54')
  }
});

var coffeeStream = coffee({bare: true})
  .on('finish', function() {
    console.log('coffee:finish');
  })
  .on('end', function() {
    console.log('coffee:end');
  });

var pass = through2.obj();

pass.pipe(coffeeStream);

pass.write(success);
pass.write(success);
pass.write(success);
pass.end();
```

```
$ node -v
> v2.3.3
$ node index.js
> coffee:finish
```

**Comment by tunnckoCore** [comment]
I think it is some wrong implementation of the tests. Given repo not seems logical and okey for me.
Actually it can be used between other streams/plugins and it filter files.

**Comment by tunnckoCore** [comment]
@shinnn yea, exactly what i started to do but with `gulp-micromatch`, so...

**Comment by tunnckoCore** [comment]
@contra rewrite all tests of `vinyl-fs` and `gulp-stream` from the ground up, it will clear a lot of things and your mind. Im sure.

**Comment by shinnn** [comment]
Or, perhaps, that is an expected behavior of Node Streams.

**Comment by yocontra** [comment]
I'm not sure how rewriting the tests for vinyl-fs are going to make this test repo start working. vinyl-fs has a dest stream it exports that needs to emit an end event. This has always been the way it functions, users rely on this behavior. Rewriting the tests to only check for a finish event and not an end event isn't going to help anyone and will break a bunch of people's code

**Comment by shinnn** [comment]
@contra I cloned the current vinyl-fs repo, downgrade vinyl-filter-since from `^2.0.2` to `^1.0.0`, and ran the test. It failed the same test, "dest stream should emit end event". So whether vinyl-filter-since uses through2 v0.6.x or readable-stream v2.x doesn't seems to be related the failing test.

**Comment by tunnckoCore** [comment]
@contra

as of

> vinyl-fs has a dest stream it exports that needs to emit an end event. 

so that

>  It failed the same test, "dest stream should emit end event"

:+1: 

> I'm not sure how rewriting the tests for vinyl-fs are going to make this test repo start working.

First, the lib works. And the issue isn't on it, neither on node streams. As you can see it also don't emits `end` event when using other plugins with that peace of code. You can keep trying with other famous plugins.

Second, rewriting would clear current mess around them and won't introduce more bugs, bugfixes and patches in future. With `tunnckoCore/glob-fs` I cover 95% of the `vinyl-fs` and `glob-stream` tests, except these that are absolutely without logic; are impossible to emulate when using correct, performant and better lib like `micromatch`; and comes from bugs and wrong understandings in `node-glob` / `minimatch` and patching their bugs.

All I'm saying is that writing clear, well organized, correct and good tests is so important as writing the lib. And you always should trying to write more and more tests, no matter coverage is 100%.

**Comment by yocontra** [comment]
I'm really at a loss for words, I don't know how else to put this.
- The project used to behave a certain way (emitting end and finish events)
- The project was updated in a PR, the behavior changed without you noticing (no longer emits end events)
- I opened a ticket to notify you that there was a regression
- You start attacking my tests on an unrelated project, as if somehow that is the culprit

I'll just stick to the old version, it worked fine. You need to rethink the way you communicate with people on github issues, this was extremely unproductive.

**Comment by tunnckoCore** [comment]
> I opened a ticket to notify you that there was a regression

I tried what I can. 

@shinnn also helps with testing and showing you that the issue is not here and not in node streams api. He also done what i've done - clone latest master branch of `vinyl-fs` and latest v2.0.2 release and it seems that it fixed the failing test, except that _"dest stream should emit end event"_ test which isn't related to `vinyl-filter-since` and is one more proof that the issue isn't here.

I will create demo repo, but we cant do more than we done to now.

I can't realize what aggression you see on my comments?
I'm just discussing and my words are just facts:
- `node-glob` is slow and bad (everyone can agree)
- `minimatch` is slow and bad (everyone can agree)
- `glob-stream` is slow cuz of above and cuz wrong architecture that you decide to implement it
- `vinyl-fs` and `gulp` continuing to add more and more streams on top of that tragedy slow core

And it's not completely your fault (your team and contribs), im sure if you replace `node-glob` one day it would be the best day and would be the real rise of Gulp. :)

**Comment by tunnckoCore** [comment]
btw, seeing that you started to use `through2-filter`, are you realizing that it also uses Streams3 API and `readable-stream@2`? lol, one more proof of what we commenting here.

**Comment by tunnckoCore** [comment]
@contra https://github.com/tunnckoCore/vinyl-fs-since with [latest master branch](https://github.com/wearefractal/vinyl-fs/commit/65090b81b98c8ed80fda247495d8015701d62813) using latest release of `vinyl-filter-since@2.0.2`
